name: Java CI with JUnit

on:
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Create directories
        run: |
          mkdir -p bin
          mkdir -p bin-tests

      - name: Compile main code
        run: |
          find src/cmd -name "*.java" > sources.txt
          javac -d bin @sources.txt

      - name: Compile tests
        run: |
          find tests -name "*.java" > test-sources.txt
          javac -d bin-tests -cp "bin:lib/*" @test-sources.txt

      - name: Run tests
        run: |
          java -cp "bin:bin-tests:lib/*" org.junit.runner.JUnitCore \
            bookingMoviesTesting.testBookingBL \
            bookingMoviesTesting.testBookingDL \
            bookingMoviesTesting.testBookingPL \
            browseMoviesTesting.testBrowsingBL \
            browseMoviesTesting.testBrowsingDL \
            browseMoviesTesting.testBrowsingPL \
            browseMoviesTesting.TestUtils \
            checkoutTesting.testCheckoutBL \
            checkoutTesting.testCheckoutDL \
            checkoutTesting.testCheckoutPL \
            manageMoviesTesting.testManageBL \
            manageMoviesTesting.testManageDL \
            manageMoviesTesting.testManagePL
